### ISSUE TITLE
Provides Bootstrap JS and CSS, not just bootswatch theme

### ISSUE THREAD

**Issue by ip2k** [dbtek/bootswatch-dist#3]
Many Bower packages depend on Bootstrap instead of bootswatch-dist, so installing such a package in combination with bootswatch-dist breaks things like modals (they close very shortly after being triggered, see http://stackoverflow.com/a/16852171 for an explanation -- this was happening to me).

Here's my `bower list`:

```
├── FileSaver#24b303f492
├─┬ bootstrap#3.3.2
│ └── jquery#2.1.3
├─┬ bootstrapValidator#0.5.3
│ ├── bootstrap#3.3.2
│ └── jquery#2.1.3
├─┬ datatables#1.10.4
│ └── jquery#2.1.3
├─┬ datatables-bootstrap3#45802ec4d3
│ └── datatables#1.10.4
├── excellentexport#aab78f4173
├── jquery#2.1.3
├── js-xlsx#0.7.11
├── papaparse#4.1.0
├─┬ select2#3.5.2 (latest is 4.0.0-beta.3)
│ └── jquery#2.1.3
└─┬ select2-bootstrap-css#1.4.6
  └── select2#3.5.2 (latest is 4.0.0-beta.3)
```

When I run `bower install bootswatch-dist#yeti --save` and then run grunt which uses wiredep to automatically insert script tags into my HTML files, bootstrap.js gets loaded twice, causing problems.

Would it be possible to have this not vendor bootstrap, and just provide the bootswatch CSS to avoid this type of conflict?

**Comment by dbtek** [comment]
Hi @ip2k,

Combining Bootswatch themes with Bootstrap sources was one objective of this project. Since Bootswatch themes are individually alternative to Bootstrap we mostly need it undivided with scripts, fonts and styles.

In this case you should exclude Bootstrap from wiredep because you welcome this dependency with bootswatch-dist.
